update 12/10/22
tientv34/MyAppFlutter pull request #1
Opened 2022-10-12 15:35 UTC by tientv34

2022-10-12 15:54 UTC, minh-dai requested changes

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +              padding:  EdgeInsets.only(right: 16,left: 16,top: screenSize.height*0.1),
please create a new class for EdgeInsets const

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                        'ログイン',
please create a new class for language, because the app will be supporting multiple language

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                          fontSize: 22,
please create a new class for fontSize

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                          return 'Error Text';
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                          return 'Error Text';
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                          return 'Error Text';
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                            borderRadius: BorderRadius.circular(4)),
please create a new class for BorderRadius

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                          setState(() {
please create a new function for this code. don't use logic code into view

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                              color: Color(0xff263645),
add color into Color class

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                        padding: EdgeInsets.only(left: 11),
a same, create a new class for EdgeInsets

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                                color: Color(0xffFFFFFF),
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                                fontSize: 17,
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                        color: Color(0xff008A7C),
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                    padding: EdgeInsets.only(left: 16,right: 16, bottom: screenSize.height*0.08),
a same

2022-10-12 15:54 UTC, minh-dai commented on lib/main.dart
> +                        fontSize: 15,
a same

2022-10-14 07:19 UTC, tientv34 commented on lib/main.dart
> +                        'ログイン',
done

2022-10-14 07:19 UTC, tientv34 commented on lib/main.dart
> +                          fontSize: 22,
done

2022-10-14 07:19 UTC, tientv34 commented on lib/main.dart
> +                          return 'Error Text';
done

2022-10-14 07:19 UTC, tientv34 commented on lib/main.dart
> +                          return 'Error Text';
done

2022-10-14 07:19 UTC, tientv34 commented on lib/main.dart
> +                                fontSize: 17,
done

2022-10-14 07:20 UTC, tientv34 commented on lib/main.dart
> +                        color: Color(0xff008A7C),
done

2022-10-14 07:20 UTC, tientv34 commented on lib/main.dart
> +                        fontSize: 15,
done

2022-10-14 07:20 UTC, tientv34 commented on lib/main.dart
> +                      child: CircularProgressIndicator(
done

2022-10-14 09:32 UTC, closed without merging